//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTPManager.FTPWebService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FTPWebService.ftpSoap")]
    public interface ftpSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_all_regions", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_all_regions();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_region_id", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Get_region_id(string regionName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_server_id", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Get_server_id(string provider, string serverAddress, string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add_server", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        object Add_server(string provider, string serverAddress, string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add_region", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        object Add_region(int serverID, string name, string fileMask, string targetDirectory, int recoveryFrequencyID, int recoveryDayID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update_region", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        object Update_region(string oldName, int serverID, string name, string fileMask, string targetDirectory, int recoveryFrequencyID, int recoveryDayID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete_region", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        object Delete_region(string regionName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_file_id", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Get_file_id(string fileName, int regionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_files_download_date", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_files_download_date(int regionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add_file", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        object Add_file(int regionID, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add_download_per_region", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        object Add_download_per_region(int regionID, int fileID, string downloadDate);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ftpSoapChannel : FTPWebService.ftpSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ftpSoapClient : System.ServiceModel.ClientBase<FTPWebService.ftpSoap>, FTPWebService.ftpSoap {
        
        public ftpSoapClient() {
        }
        
        public ftpSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ftpSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ftpSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ftpSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet Get_all_regions() {
            return base.Channel.Get_all_regions();
        }
        
        public int Get_region_id(string regionName) {
            return base.Channel.Get_region_id(regionName);
        }
        
        public int Get_server_id(string provider, string serverAddress, string login, string password) {
            return base.Channel.Get_server_id(provider, serverAddress, login, password);
        }
        
        public object Add_server(string provider, string serverAddress, string login, string password) {
            return base.Channel.Add_server(provider, serverAddress, login, password);
        }
        
        public object Add_region(int serverID, string name, string fileMask, string targetDirectory, int recoveryFrequencyID, int recoveryDayID) {
            return base.Channel.Add_region(serverID, name, fileMask, targetDirectory, recoveryFrequencyID, recoveryDayID);
        }
        
        public object Update_region(string oldName, int serverID, string name, string fileMask, string targetDirectory, int recoveryFrequencyID, int recoveryDayID) {
            return base.Channel.Update_region(oldName, serverID, name, fileMask, targetDirectory, recoveryFrequencyID, recoveryDayID);
        }
        
        public object Delete_region(string regionName) {
            return base.Channel.Delete_region(regionName);
        }
        
        public int Get_file_id(string fileName, int regionID) {
            return base.Channel.Get_file_id(fileName, regionID);
        }
        
        public System.Data.DataSet Get_files_download_date(int regionId) {
            return base.Channel.Get_files_download_date(regionId);
        }
        
        public object Add_file(int regionID, string name) {
            return base.Channel.Add_file(regionID, name);
        }
        
        public object Add_download_per_region(int regionID, int fileID, string downloadDate) {
            return base.Channel.Add_download_per_region(regionID, fileID, downloadDate);
        }
    }
}
